// domain/pedidoModel.js

const toNumberOrNull = (value) => {
  if (value === null || value === undefined || value === '') return null;
  const normalizedValue = typeof value === 'string' ? value.replace(',', '.') : value;
  const numberValue = Number(normalizedValue);
  return Number.isNaN(numberValue) ? null : numberValue;
};

export const createPedido = ({
  idPedido,
  idCotizacion,
  idCliente,
  estadoPedido   = 'PENDIENTE',
  estadoPago     = 'PENDIENTE',
  total          = 0,
  subtotal       = null,
  subtotalBruto  = null,
  subtotalConDescuento = null,
  subtotalFinal  = null,
  descuentoTotal = null,
  costosAdicionales = null,
  costoDiseno = null,
  totalPagado    = 0,
  saldoPendiente = 0,
  fechaCreacion,
  fechaActualizacion    = null,
  fechaEntregaEstimada = null,
  fechaFinalizado      = null,
  fechaEntregado       = null,
  observaciones        = null,
  cliente    = null,
  cotizacion = null,
  detalles   = [],
  disenos    = [],
  abonos     = [],
}) => ({
  idPedido,
  idCotizacion,
  idCliente,
  estadoPedido,
  estadoPago,
  total:          Number(total),
  subtotal:       toNumberOrNull(subtotal),
  subtotalBruto:  toNumberOrNull(subtotalBruto),
  subtotalConDescuento: toNumberOrNull(subtotalConDescuento),
  subtotalFinal:  toNumberOrNull(subtotalFinal),
  descuentoTotal: toNumberOrNull(descuentoTotal),
  costosAdicionales: toNumberOrNull(costosAdicionales),
  costoDiseno: toNumberOrNull(costoDiseno),
  totalPagado:    Number(totalPagado),
  saldoPendiente: Number(saldoPendiente),
  fechaCreacion,
  fechaActualizacion,
  fechaEntregaEstimada,
  fechaFinalizado,
  fechaEntregado,
  observaciones,
  cliente,
  cotizacion,
  detalles,
  disenos: Array.isArray(disenos) ? disenos : [],
  abonos,
});

export const createDetallePedido = ({
  idDetallePedido,
  idPedido,
  idTecnica,
  descripcion,
  cantidad       = 1,
  precioUnitario = 0,
  precioBase     = null,
  descuentoPorcentaje = null,
  descuentoValorUnitario = null,
  descuentoTotal = null,
  costoDiseno    = null,
  subtotal       = 0,
  subtotalBruto  = null,
  subtotalConDescuento = null,
  subtotalFinal  = null,
  observaciones  = null,
  requiereDiseno = true,
  disenos        = [],
  producto        = null,
  tecnica        = null,
}) => ({
  idDetallePedido,
  idPedido,
  idTecnica,
  descripcion,
  cantidad:       Number(cantidad),
  precioBase:     toNumberOrNull(precioBase),
  descuentoPorcentaje: toNumberOrNull(descuentoPorcentaje),
  descuentoValorUnitario: toNumberOrNull(descuentoValorUnitario),
  descuentoTotal: toNumberOrNull(descuentoTotal),
  costoDiseno:    toNumberOrNull(costoDiseno),
  precioUnitario: Number(precioUnitario),
  subtotal:       Number(subtotal),
  subtotalBruto:  toNumberOrNull(subtotalBruto),
  subtotalConDescuento: toNumberOrNull(subtotalConDescuento),
  subtotalFinal: toNumberOrNull(subtotalFinal),
  observaciones,
  requiereDiseno: requiereDiseno !== false,
  disenos: Array.isArray(disenos) ? disenos : (disenos ? [disenos] : []),
  producto,
  tecnica,
});
