// domain/pedidoModel.js

export const createPedido = ({
  idPedido,
  idCotizacion,
  idCliente,
  estadoPedido   = 'PENDIENTE',
  estadoPago     = 'PENDIENTE',
  total          = 0,
  totalPagado    = 0,
  saldoPendiente = 0,
  fechaCreacion,
  fechaEntregaEstimada = null,
  fechaFinalizado      = null,
  fechaEntregado       = null,
  observaciones        = null,
  cliente    = null,
  cotizacion = null,
  detalles   = [],
  abonos     = [],
}) => ({
  idPedido,
  idCotizacion,
  idCliente,
  estadoPedido,
  estadoPago,
  total:          Number(total),
  totalPagado:    Number(totalPagado),
  saldoPendiente: Number(saldoPendiente),
  fechaCreacion,
  fechaEntregaEstimada,
  fechaFinalizado,
  fechaEntregado,
  observaciones,
  cliente,
  cotizacion,
  detalles,
  abonos,
});

export const createDetallePedido = ({
  idDetallePedido,
  idPedido,
  idTecnica,
  descripcion,
  cantidad       = 1,
  precioUnitario = 0,
  subtotal       = 0,
  observaciones  = null,
  tecnica        = null,
}) => ({
  idDetallePedido,
  idPedido,
  idTecnica,
  descripcion,
  cantidad:       Number(cantidad),
  precioUnitario: Number(precioUnitario),
  subtotal:       Number(subtotal),
  observaciones,
  tecnica,
});