export const createAbono = ({
  idAbono,
  idPedido,
  monto = null,
  metodoPago,
  referencia = '',
  fechaPago = null,
  comprobanteUrl = '',
  comprobanteDisponible = false,
  nombreOriginalComprobante = '',
  comprobanteMimeType = '',
  comprobanteSizeBytes = null,
  comprobanteSubidoEn = null,
  montoDetectadoOcr = null,
  referenciaDetectadaOcr = '',
  fechaDetectadaOcr = null,
  bancoDetectadoOcr = '',
  confianzaOcr = null,
  requiereRevisionManual = false,
  origenRegistro = '',
  observaciones = '',
  estado = 'PENDIENTE',
  fechaCreacion,
  confirmadoPorId = null,
  fechaConfirmacion = null,
  rechazadoPorId = null,
  fechaRechazo = null,
  motivoRechazo = null,
  pedido = null,
  confirmadoPor = null,
  rechazadoPor = null,
}) => ({
  idAbono,
  idPedido,
  monto: monto === null || monto === undefined || monto === '' ? null : Number(monto),
  metodoPago,
  referencia: referencia || '',
  fechaPago,
  comprobanteUrl: comprobanteUrl || '',
  comprobanteDisponible: Boolean(comprobanteDisponible || comprobanteUrl || nombreOriginalComprobante),
  nombreOriginalComprobante: nombreOriginalComprobante || '',
  comprobanteMimeType: comprobanteMimeType || '',
  comprobanteSizeBytes: comprobanteSizeBytes == null ? null : Number(comprobanteSizeBytes),
  comprobanteSubidoEn,
  montoDetectadoOcr: montoDetectadoOcr == null ? null : Number(montoDetectadoOcr),
  referenciaDetectadaOcr: referenciaDetectadaOcr || '',
  fechaDetectadaOcr,
  bancoDetectadoOcr: bancoDetectadoOcr || '',
  confianzaOcr: confianzaOcr == null ? null : Number(confianzaOcr),
  requiereRevisionManual: Boolean(requiereRevisionManual),
  origenRegistro: origenRegistro || '',
  observaciones: observaciones || '',
  estado,
  fechaCreacion,
  confirmadoPorId,
  fechaConfirmacion,
  rechazadoPorId,
  fechaRechazo,
  motivoRechazo,
  pedido,
  confirmadoPor,
  rechazadoPor,
});
