export const createAbono = ({
  idAbono,
  idPedido,
  monto = 0,
  metodoPago,
  referencia = '',
  comprobanteUrl = '',
  estado = 'PENDIENTE',
  fechaCreacion,
  confirmadoPorId = null,
  fechaConfirmacion = null,
  rechazadoPorId = null,
  fechaRechazo = null,
  motivoRechazo = null,
  pedido = null,
  confirmadoPor = null,
  rechazadoPor = null,
}) => ({
  idAbono,
  idPedido,
  monto: Number(monto || 0),
  metodoPago,
  referencia: referencia || '',
  comprobanteUrl: comprobanteUrl || '',
  estado,
  fechaCreacion,
  confirmadoPorId,
  fechaConfirmacion,
  rechazadoPorId,
  fechaRechazo,
  motivoRechazo,
  pedido,
  confirmadoPor,
  rechazadoPor,
});
