const toNullableNumber = value => {
  if (value === null || value === undefined || value === '') return null;
  const numericValue = Number(value);
  return Number.isFinite(numericValue) ? numericValue : null;
};

export const createAbono = ({
  idAbono,
  idPedido,
  monto = null,
  metodoPago,
  referencia = '',
  fechaPago = null,
  comprobanteUrl = '',
  comprobanteDisponible = false,
  nombreOriginalComprobante = '',
  comprobanteMimeType = '',
  comprobanteSizeBytes = null,
  comprobanteSubidoEn = null,
  montoDetectadoOcr = null,
  referenciaDetectadaOcr = '',
  fechaDetectadaOcr = null,
  bancoDetectadoOcr = '',
  confianzaOcr = null,
  calidadLectura = null,
  requiereRevisionManual = false,
  origenAnalisis = '',
  origenRegistro = '',
  origenRegistroCodigo = '',
  origenRegistroLabel = '',
  datosDetectados = null,
  datosDefinitivos = null,
  totalPedido = null,
  totalConfirmado = null,
  saldoPendiente = null,
  estadoPago = '',
  observaciones = '',
  estado = 'PENDIENTE',
  fechaCreacion,
  confirmadoPorId = null,
  fechaConfirmacion = null,
  rechazadoPorId = null,
  fechaRechazo = null,
  motivoRechazo = null,
  pedido = null,
  confirmadoPor = null,
  rechazadoPor = null,
}) => ({
  idAbono,
  idPedido,
  monto: toNullableNumber(monto),
  metodoPago,
  referencia: referencia || '',
  fechaPago,
  comprobanteUrl: comprobanteUrl || '',
  comprobanteDisponible: Boolean(comprobanteDisponible || comprobanteUrl || nombreOriginalComprobante),
  nombreOriginalComprobante: nombreOriginalComprobante || '',
  comprobanteMimeType: comprobanteMimeType || '',
  comprobanteSizeBytes: toNullableNumber(comprobanteSizeBytes),
  comprobanteSubidoEn,
  montoDetectadoOcr: toNullableNumber(montoDetectadoOcr),
  referenciaDetectadaOcr: referenciaDetectadaOcr || '',
  fechaDetectadaOcr,
  bancoDetectadoOcr: bancoDetectadoOcr || '',
  confianzaOcr: toNullableNumber(confianzaOcr),
  calidadLectura: toNullableNumber(calidadLectura),
  requiereRevisionManual: Boolean(requiereRevisionManual),
  origenAnalisis: origenAnalisis || '',
  origenRegistro: origenRegistro || '',
  origenRegistroCodigo: origenRegistroCodigo || origenRegistro || '',
  origenRegistroLabel: origenRegistroLabel || '',
  datosDetectados,
  datosDefinitivos,
  totalPedido: toNullableNumber(totalPedido),
  totalConfirmado: toNullableNumber(totalConfirmado),
  saldoPendiente: toNullableNumber(saldoPendiente),
  estadoPago: estadoPago || '',
  observaciones: observaciones || '',
  estado,
  fechaCreacion,
  confirmadoPorId,
  fechaConfirmacion,
  rechazadoPorId,
  fechaRechazo,
  motivoRechazo,
  pedido,
  confirmadoPor,
  rechazadoPor,
});
