export const createVenta = ({
  idPedido,
  idVenta = null,
  idCliente,
  nombreCliente = '',
  correoCliente = '',
  telefonoCliente = '',
  total = 0,
  totalPagado = 0,
  saldoPendiente = 0,
  estado = null,
  fechaPrimerPago = null,
  fechaCreacion = null,
  fechaFinalizado = null,
  fechaEntregado = null,
  estadoPago = 'PENDIENTE',
  tecnicas = [],
  cantidadTotalProductos = 0,
} = {}) => ({
  idPedido,
  idVenta,
  idCliente,
  nombreCliente,
  correoCliente,
  telefonoCliente,
  total,
  totalPagado,
  saldoPendiente,
  estado,
  fechaPrimerPago,
  fechaCreacion,
  fechaFinalizado,
  fechaEntregado,
  estadoPago,
  tecnicas,
  cantidadTotalProductos,
});
