export const createDiseno = ({
  idDiseno,
  idPedido,
  idDisenador = null,
  archivoUrl = '',
  descripcion = '',
  observaciones = '',
  estado = 'PENDIENTE',
  fechaCreacion,
  fechaActualizacion = null,
  fechaEnvio = null,
  fechaAprobacion = null,
  pedido = null,
  disenador = null,
}) => ({
  idDiseno,
  idPedido,
  idDisenador,
  archivoUrl: archivoUrl || '',
  descripcion: descripcion || '',
  observaciones: observaciones || '',
  estado,
  fechaCreacion,
  fechaActualizacion,
  fechaEnvio,
  fechaAprobacion,
  pedido,
  disenador,
});
