export const createDiseno = ({
  idDiseno,
  idPedido,
  idDisenador = null,
  archivoUrl = '',
  descripcion = '',
  observaciones = '',
  origenDiseno = 'DISENADOR',
  medioRecepcion = '',
  recibidoPorId = null,
  recibidoPor = null,
  estado = 'PENDIENTE',
  fechaCreacion,
  fechaActualizacion = null,
  fechaEnvio = null,
  fechaRecepcion = null,
  fechaAprobacion = null,
  fechaRespuestaCliente = null,
  observacionesCliente = '',
  medioAprobacion = '',
  medioRespuesta = '',
  medioRespuestaCliente = '',
  respuestaRegistradaPor = null,
  pedido = null,
  disenador = null,
}) => ({
  idDiseno,
  idPedido,
  idDisenador,
  archivoUrl: archivoUrl || '',
  descripcion: descripcion || '',
  observaciones: observaciones || '',
  origenDiseno: origenDiseno || 'DISENADOR',
  medioRecepcion: medioRecepcion || '',
  recibidoPorId,
  recibidoPor,
  estado,
  fechaCreacion,
  fechaActualizacion,
  fechaEnvio,
  fechaRecepcion,
  fechaAprobacion,
  fechaRespuestaCliente,
  observacionesCliente: observacionesCliente || '',
  medioAprobacion: medioAprobacion || '',
  medioRespuesta: medioRespuesta || '',
  medioRespuestaCliente: medioRespuestaCliente || '',
  respuestaRegistradaPor,
  pedido,
  disenador,
});
