// domain/quotesModel.js
export const createQuote = ({
  idCotizacion,
  idCliente,
  creadoPorId,
  tipoCotizacion = "NORMAL",
  estado = "PENDIENTE", // Actualizado al nuevo enum del backend
  subtotal = 0,
  subtotalBruto = null,
  descuentoTotal = null,
  subtotalConDescuento = null,
  subtotalFinal = null,
  costoDiseno = 0,
  costosAdicionales = 0,
  total = 0,
  cantidadItems = null,
  productosResumen = '',
  observaciones = "",
  observacionesInternas = "",
  precioSugeridoInterno = null,
  precioSugeridoSistema = null,
  calculoCompleto = null,
  requiereRevisionPrecio = false,
  advertenciasInternas = [],
  disenosPropuesta = [],
  conceptosAdicionales = [],
  estadoPrecio = null,
  propuestaActual = null,
  propuesta = null,
  versiones = [],
  fechaCreacion,
  cliente,
  creadoPor,
  detalles = []
}) => {
  return {
    idCotizacion, // Usamos la propiedad exacta del backend
    idCliente,
    creadoPorId,
    tipoCotizacion,
    estado,
    subtotal: Number(subtotal),
    subtotalBruto: subtotalBruto !== null && subtotalBruto !== undefined ? Number(subtotalBruto) : null,
    descuentoTotal: descuentoTotal !== null && descuentoTotal !== undefined ? Number(descuentoTotal) : null,
    subtotalConDescuento: subtotalConDescuento !== null && subtotalConDescuento !== undefined ? Number(subtotalConDescuento) : null,
    subtotalFinal: subtotalFinal !== null && subtotalFinal !== undefined ? Number(subtotalFinal) : null,
    costoDiseno: Number(costoDiseno || 0),
    costosAdicionales: Number(costosAdicionales),
    total: Number(total),
    cantidadItems: cantidadItems !== null && cantidadItems !== undefined ? Number(cantidadItems) : detalles.length,
    productosResumen: productosResumen || '',
    observaciones: observaciones || "",
    observacionesInternas: observacionesInternas || "",
    precioSugeridoInterno: precioSugeridoInterno !== null && precioSugeridoInterno !== undefined
      ? Number(precioSugeridoInterno)
      : null,
    precioSugeridoSistema: precioSugeridoSistema !== null && precioSugeridoSistema !== undefined
      ? Number(precioSugeridoSistema)
      : null,
    calculoCompleto,
    requiereRevisionPrecio: Boolean(requiereRevisionPrecio),
    advertenciasInternas: Array.isArray(advertenciasInternas) ? advertenciasInternas : [],
    disenosPropuesta: Array.isArray(disenosPropuesta) ? disenosPropuesta : [],
    conceptosAdicionales: Array.isArray(conceptosAdicionales) ? conceptosAdicionales : [],
    estadoPrecio,
    propuestaActual,
    propuesta,
    versiones: Array.isArray(versiones) ? versiones : [],
    fechaCreacion,
    cliente,
    creadoPor,
    detalles
  };
};

export const createQuoteDetail = ({
  idDetalleCotizacion,
  idCotizacion,
  idProducto,
  idTecnica,
  descripcion,
  cantidad = 1,
  precioBase = null,
  descuentoPorcentaje = null,
  descuentoValorUnitario = null,
  descuentoTotal = null,
  precioUnitario = null, // Puede ser null inicialmente en el backend
  costoDiseno = 0,
  requiereDiseno = true,
  origenDiseno = 'PIXEL',
  esDisenoGeneral = false,
  archivoDisenoInicialUrl = '',
  subtotal = null,
  subtotalBruto = null,
  subtotalConDescuento = null,
  subtotalFinal = null,
  imagenReferencia = "",
  observaciones = "",
  producto,
  tecnica,
  tipoProducto = 'CATALOGO',
  nombrePersonalizado = null,
  descripcionPersonalizada = '',
  materialReferencia = '',
  suministradoPor = 'PIXEL',
  estampados = [],
  requiereRevisionPrecio = false,
  calculoCompleto = null,
  estadoMedidas = null,
  motivosRevision = [],
  rangoProductoAplicado = null,
  precioSugeridoInterno = null,
  subtotalSugeridoInterno = null,
  subtotalServiciosOficial = null,
  costoProducto = 0,
  otrosCostosItem = 0,
  subtotalOficial = null
}) => {
  return {
    idDetalleCotizacion, // Exactamente como Prisma select
    idCotizacion,
    idProducto,
    idTecnica,
    descripcion,
    cantidad: parseInt(cantidad, 10),
    precioBase: precioBase !== null ? Number(precioBase) : null,
    descuentoPorcentaje: descuentoPorcentaje !== null && descuentoPorcentaje !== undefined && descuentoPorcentaje !== ''
      ? Number(String(descuentoPorcentaje).replace(',', '.'))
      : null,
    descuentoValorUnitario: descuentoValorUnitario !== null && descuentoValorUnitario !== undefined && descuentoValorUnitario !== ''
      ? Number(descuentoValorUnitario)
      : null,
    descuentoTotal: descuentoTotal !== null && descuentoTotal !== undefined && descuentoTotal !== ''
      ? Number(descuentoTotal)
      : null,
    precioUnitario: precioUnitario !== null ? Number(precioUnitario) : null,
    costoDiseno: Number(costoDiseno || 0),
    requiereDiseno: requiereDiseno !== false,
    origenDiseno: origenDiseno || 'PIXEL',
    esDisenoGeneral: Boolean(esDisenoGeneral),
    archivoDisenoInicialUrl: archivoDisenoInicialUrl || '',
    subtotal: subtotal !== null ? Number(subtotal) : null,
    subtotalBruto: subtotalBruto !== null && subtotalBruto !== undefined ? Number(subtotalBruto) : null,
    subtotalConDescuento: subtotalConDescuento !== null && subtotalConDescuento !== undefined ? Number(subtotalConDescuento) : null,
    subtotalFinal: subtotalFinal !== null && subtotalFinal !== undefined ? Number(subtotalFinal) : null,
    imagenReferencia: imagenReferencia || "",
    observaciones: observaciones || "",
    producto,
    tecnica,
    tipoProducto,
    nombrePersonalizado,
    descripcionPersonalizada: descripcionPersonalizada || '',
    materialReferencia: materialReferencia || '',
    suministradoPor,
    estampados: Array.isArray(estampados) ? estampados : [],
    requiereRevisionPrecio: Boolean(requiereRevisionPrecio),
    calculoCompleto,
    estadoMedidas,
    motivosRevision: Array.isArray(motivosRevision) ? motivosRevision : [],
    rangoProductoAplicado,
    precioSugeridoInterno: precioSugeridoInterno == null ? null : Number(precioSugeridoInterno),
    subtotalSugeridoInterno: subtotalSugeridoInterno == null ? null : Number(subtotalSugeridoInterno),
    subtotalServiciosOficial: subtotalServiciosOficial == null ? null : Number(subtotalServiciosOficial),
    costoProducto: Number(costoProducto || 0),
    otrosCostosItem: Number(otrosCostosItem || 0),
    subtotalOficial: subtotalOficial == null ? null : Number(subtotalOficial)
  };
};
